spring:
  datasource:
    username: root
    password: springcourse
    url: jdbc:mysql://mysql-db:3306/learning_center?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
